### PR TITLE
Aws ssm connection plugin

### PR DESCRIPTION
**Pull request by raphaelschnaitl**
Fixed some encoding and power shell control char problems as described here. https://github.com/ansible/ansible/pull/49652. 

Fixed all requested changes on the pull request.

### CODE REVIEW

**Comment by raphaelschnaitl** [comment]
Hi @psharkey can you merge this changes into your PR?

**Comment by psharkey** [comment]
@Console32 Can you squash your commits and provide a log of the integration tests? I can just cherry-pick the squashed commit then to avoid a merge commit in https://github.com/ansible/ansible/pull/49652.

**Comment by raphaelschnaitl** [comment]
@psharkey Sorry for the delayed response. 
I am unable to run the integration test on my machine (macOS). I keep getting errors with the docker images.

**Comment by hanumantharaomvl** [comment]
@Console32 , I have used this branch for the integration tests for both linux & windows and failing at initial stages with the same error i mentioned at https://github.com/ansible/ansible/pull/49652#issuecomment-566598019. 

As I have mentioned in the PR page, the **only** issue remains and blocker for us is https://github.com/ansible/ansible/pull/49652#issuecomment-559833467 for `windows alone` and all the remaining integration tests passing for both linux and windows. Can you review once ?

**Comment by hanumantharaomvl** [comment]
@Console32 , After reverting back these (https://github.com/Console32/ansible/blob/aws_ssm-connection-plugin/lib/ansible/plugins/connection/aws_ssm.py#L364-L369) changes to original, windows integration test is failing with following error. Passing for linux as it was before.

```
<i-0e827047800d88172> TERMINATE SSM SESSION: hanumanth@flux7.com-0870dfee5fe7c3d9b
The full traceback is:
Traceback (most recent call last):
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 650, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/ansible/lib/ansible/plugins/action/raw.py", line 42, in run
    result.update(self._low_level_execute_command(self._task.args.get('_raw_params'), executable=executable))
  File "/root/ansible/lib/ansible/plugins/action/__init__.py", line 1052, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/root/ansible/lib/ansible/plugins/connection/aws_ssm.py", line 189, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/root/ansible/lib/ansible/plugins/connection/aws_ssm.py", line 374, in exec_command
    returncode, stdout = self._post_process(stdout)
  File "/root/ansible/lib/ansible/plugins/connection/aws_ssm.py", line 408, in _post_process
    returncode = int(stdout.splitlines()[-1])
ValueError: invalid literal for int() with base 10: '汉语'

fatal: [i-0e827047800d88172]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by raphaelschnaitl** [comment]
@hanumantharaomvl Thanks for taking a look, I do not know why this keeps failing. 

I can not reproduce the issue, I am unable to execute the integration test on my machine. And I am still stuck with the issue I mentioned here: https://github.com/ansible/ansible/pull/49652#issuecomment-559788843

**Comment by jitteryjuice** [comment]
> @hanumantharaomvl Thanks for taking a look, I do not know why this keeps failing.
> 
> I can not reproduce the issue, I am unable to execute the integration test on my machine. And I am still stuck with the issue I mentioned here: [ansible#49652 (comment)](https://github.com/ansible/ansible/pull/49652#issuecomment-559788843)

This is failing due to the raw command not returning an exit code (and LASTEXITCODE is not defined).

**Pull request closed without merging**
